import React, {useState} from 'react';
import {useClinic} from '../store';

const labels={doctor:'Khám bệnh',scribe:'Hồ sơ khám · Thư ký',nurse:'Điều dưỡng',ultrasound:'Siêu âm',lab:'Xét nghiệm'};
const stageNames={booking:'Đã đặt lịch',waiting:'Đang chờ',vitals:'Sinh hiệu',exam:'Đang khám',services:'Làm dịch vụ',review:'Chờ đọc kết quả',checkout:'Chờ ra về',departed:'Đã ra về'};
const sections=['Lý do khám','Bệnh sử và tiền sử','Khám lâm sàng','Nhận định / chẩn đoán','Kế hoạch và lời dặn'];
function parseNote(note=''){const values={}; sections.forEach((label,i)=>{const prefix=label+':\n'; const start=note.indexOf(prefix); if(start>=0){const end=i<sections.length-1?note.indexOf('\n\n'+sections[i+1]+':',start):-1; values[label]=note.slice(start+prefix.length,end>=0?end:undefined);}}); if(!Object.keys(values).length) values[sections[0]]=note; return values;}
function Status({children}){return <span className="badge">{children}</span>}
function ClinicalRecord({patient:p,role,data,act}){
 const [form,setForm]=useState(()=>parseNote(p.note));
 const [loaded,setLoaded]=useState(p.version||0);
 const [tab,setTab]=useState('record');
 const [message,setMessage]=useState('');
 const [dirty,setDirty]=useState(false);
 const [service,setService]=useState('Siêu âm');
 const [drug,setDrug]=useState('');
 const [quantity,setQuantity]=useState(1);
 const isDoctor=role==='doctor';
 const stale=loaded!==(p.version||0);
 const run=(type,payload)=>{const r=act(type,{id:p.id,...payload});setMessage(r?.ok===false?r.error:'Đã cập nhật hồ sơ.');return r;};
 const save=()=>{const r=run('saveNote',{note:sections.map(k=>`${k}:\n${form[k]||''}`).join('\n\n'),expectedVersion:loaded});if(r?.ok!==false){setLoaded((p.version||0)+1);setDirty(false);}};
 const reload=()=>{setForm(parseNote(p.note));setLoaded(p.version||0);setDirty(false);setMessage('Đã tải phiên bản mới nhất.');};
 return <>
  <div className="toolbar"><div><h2>{p.name}</h2><p className="muted">{p.id} · {p.dob||'Chưa bổ sung ngày sinh'} · {p.phone} · {p.service}</p></div><Status>{stageNames[p.stage]||p.status}</Status></div>
  <div className="card" style={{background:'#eef8f5',marginBottom:16}}><strong>Hồ sơ chung của bác sĩ và thư ký</strong><p className="muted">Người nhập được ghi nhận riêng. Bác sĩ kiểm tra và xác nhận quyết định chuyên môn. Phiên bản đang xem: {loaded} · Phiên bản hồ sơ: {p.version||0} · {p.approvedVersion===p.version?'Đã được bác sĩ duyệt':'Chưa duyệt bản hiện tại'}.</p>{stale&&<div role="alert"><strong>Hồ sơ vừa thay đổi ở màn làm việc khác.</strong> <button className="btn" onClick={reload}>Tải thay đổi để kiểm tra</button></div>}</div>
  <div className="tabs">{[['record','Hồ sơ khám'],['orders','Chỉ định & kết quả'],['prescription','Đơn thuốc'],['history','Lịch sử thao tác']].map(([v,t])=><button className={tab===v?'active':''} onClick={()=>setTab(v)} key={v}>{t}</button>)}</div>
  {tab==='record'&&<div className="card"><div className="toolbar"><h3>Nội dung lần khám</h3><button className="btn" onClick={reload}>Tải bản đã lưu</button></div><div className="grid2">{sections.map((label,i)=><label className="field" key={label} style={i===4?{gridColumn:'1/-1'}:{}}>{label}<textarea rows={i===0?3:5} value={form[label]||''} onChange={e=>{setForm({...form,[label]:e.target.value});setDirty(true);}} placeholder={i===0?'Ghi nhận lời kể của người bệnh':i===3?'Thư ký ghi theo ý kiến bác sĩ; bác sĩ kiểm tra trước khi duyệt':'Nhập nội dung của lần khám'}/></label>)}</div><div className="toolbar"><div><button className="btn primary" onClick={save} disabled={stale}>Lưu nội dung</button> <button className="btn" onClick={()=>run('startExam',{})} disabled={p.stage==='exam'}>Bắt đầu khám</button></div><button className="btn primary" disabled={!isDoctor||stale||dirty||!p.note} title={!isDoctor?'Chỉ bác sĩ được xác nhận chuyên môn':stale?'Cần tải và xem lại thay đổi mới':''} onClick={()=>run('approve',{expectedVersion:loaded})}>Bác sĩ xác nhận bản {loaded}</button></div>{dirty&&<p className="muted">Có nội dung chưa lưu. Lưu trước khi xác nhận phiên bản hồ sơ.</p>}{!isDoctor&&<p className="muted">Bạn có thể nhập và sửa theo lời bác sĩ. Quyền xác nhận cuối thuộc bác sĩ.</p>}</div>}
  {tab==='orders'&&<div className="card"><h3>Chỉ định trong lần khám</h3><div className="toolbar"><select value={service} onChange={e=>setService(e.target.value)}>{['Siêu âm','Xét nghiệm máu','Xét nghiệm nước tiểu','DXA','Monitoring','Thủ thuật','Chụp ngoài'].map(s=><option key={s}>{s}</option>)}</select><button className="btn primary" disabled={stale||dirty} onClick={()=>run('draftOrder',{kind:service})}>Thêm chỉ định {isDoctor?'':'theo bác sĩ'}</button></div><p className="muted">Chỉ định thêm vào là bản nháp. Sau khi thêm, tải và kiểm tra phiên bản mới rồi bác sĩ xác nhận tại Hồ sơ khám; khi đó dịch vụ mới được thực hiện.</p><div className="table-wrap"><table className="table"><thead><tr><th>Dịch vụ</th><th>Trạng thái</th><th>Kết quả</th><th>Bác sĩ đọc</th></tr></thead><tbody>{(p.orders||[]).map(o=><tr key={o.id}><td>{o.kind}<small className="muted" style={{display:'block'}}>{o.id}</small></td><td><Status>{o.status==='draft'?'Nháp · chưa được thực hiện':o.status==='ordered'?'Đã duyệt · chờ thực hiện':o.status==='sampled'?'Đã nhận mẫu':o.status==='received'?'Đã có kết quả':o.status}</Status></td><td>{o.result||'Chưa có kết quả'}</td><td><button className="btn" disabled={!isDoctor||!o.result||o.reviewed} onClick={()=>run('reviewResult',{orderId:o.id})}>{o.reviewed?'Đã đọc':'Xác nhận đã đọc'}</button></td></tr>)}</tbody></table>{!p.orders?.length&&<p className="empty">Chưa có chỉ định trong lần khám này.</p>}</div><div className="toolbar"><p className="muted">Nhận kết quả, bác sĩ đọc và phát hành cho khách là ba bước riêng biệt.</p><button className="btn" disabled={!isDoctor||stale||dirty||p.approvedVersion!==p.version||p.released||p.orders.some(o=>!o.reviewed)} onClick={()=>run('release',{})}>{p.released?'Đã phát hành':'Phát hành kết quả đã duyệt'}</button></div></div>}
  {tab==='prescription'&&<div className="card"><h3>Đơn thuốc của lần khám</h3><div className="toolbar"><select value={drug} onChange={e=>setDrug(e.target.value)}><option value="">Chọn thuốc trong danh mục</option>{(data.drugs||[]).map(d=><option value={d.id} key={d.id}>{d.name} · Tồn {d.stock??'—'}</option>)}</select><label className="field">Số lượng<input type="number" min="1" max="500" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button className="btn primary" disabled={!drug||Number(quantity)<1||stale||dirty} onClick={()=>run('draftPrescribe',{drugId:drug,quantity:Number(quantity)})}>Thêm vào đơn</button></div><p className="muted">Thư ký nhập theo bác sĩ. Sau khi thêm thuốc, tải phiên bản mới và để bác sĩ xác nhận tại Hồ sơ khám trước khi cấp. Liều dùng phải được bác sĩ xác định.</p><table className="table"><thead><tr><th>Thuốc</th><th>Số lượng</th><th>Trạng thái duyệt</th></tr></thead><tbody>{(p.prescription||[]).map((d,i)=><tr key={i}><td>{d.name||(data.drugs||[]).find(x=>x.id===d.drugId)?.name||d.drugId}</td><td>{d.quantity}</td><td>{d.approvedVersion===p.version&&p.approvedVersion===p.version?'Đã duyệt · được cấp':'Nháp · chưa được cấp'}</td></tr>)}</tbody></table>{!p.prescription?.length&&<p className="empty">Chưa kê thuốc.</p>}</div>}
  {tab==='history'&&<div className="card"><h3>Dấu vết hồ sơ</h3>{(data.events||[]).filter(e=>e.patientId===p.id||e.entityId===p.id||e.id===p.id).slice().map((e,i)=><div key={i} style={{borderBottom:'1px solid #e5e9ef',padding:'12px 0'}}><strong>{e.label||e.type||e.action}</strong><p className="muted">{e.actor||e.role} · {e.time||e.at} {typeof e.detail==='object'?Object.entries(e.detail).map(([k,v])=>`${k}: ${v}`).join(' · '):e.detail||e.message||''}</p></div>)}<p className="muted">Người nhập, người quyết định chuyên môn, phiên bản và thời điểm xác nhận được ghi riêng.</p></div>}
  {message&&<p role="status" className="card" style={{marginTop:12}}>{message}</p>}
 </>;
}
function Vitals({patient:p,act}){
 const [v,setV]=useState(()=>({...p.vitals,systolic:p.vitals?.systolic||p.vitals?.bp?.split('/')[0]||'',diastolic:p.vitals?.diastolic||p.vitals?.bp?.split('/')[1]||''}));const [identity,setIdentity]=useState(false);const [message,setMessage]=useState('');
 const fields=[['systolic','Huyết áp tâm thu','mmHg'],['diastolic','Huyết áp tâm trương','mmHg'],['pulse','Mạch','lần/phút'],['temperature','Nhiệt độ','°C'],['weight','Cân nặng','kg'],['height','Chiều cao','cm'],['spo2','SpO₂','%'],['respiratory','Nhịp thở','lần/phút']];
 return <div className="card"><h2>{p.name} · Sinh hiệu</h2><p className="muted">{p.id} · {p.phone} · {p.dob||'Ngày sinh chưa bổ sung'}</p><label className="field" style={{margin:'18px 0'}}><span><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)}/> Đã đối chiếu ít nhất hai thông tin nhận diện với người bệnh</span></label><div className="grid3">{fields.map(([k,label,unit])=><label className="field" key={k}>{label} {['systolic','diastolic'].includes(k)&&'*'}<input type="number" step="0.1" min="0" value={v[k]??''} placeholder={unit} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</div><p className="muted">Huyết áp cần được đo cho mỗi lượt. Các phép đo chưa làm để trống, không thay bằng số 0.</p><button className="btn primary" disabled={!identity||!v.systolic||!v.diastolic||Number(v.systolic)<=Number(v.diastolic)} onClick={()=>{const r=act('vitals',{id:p.id,values:v});setMessage(r?.ok===false?r.error:'Đã lưu sinh hiệu và cập nhật hồ sơ chung.')}}>Lưu sinh hiệu & chuyển điều phối</button>{message&&<p role="status">{message}</p>}</div>;
}
function ServiceResults({patient:p,role,act}){
 const [selected,setSelected]=useState(''); const [report,setReport]=useState('');const [file,setFile]=useState('');const [identity,setIdentity]=useState(false);const [message,setMessage]=useState('');
 const orders=(p.orders||[]).filter(o=>role==='ultrasound'?/siêu|ultra|^sa$/i.test(o.kind):role==='nurse'?/DXA|Monitoring|Thủ thuật|Chụp ngoài/i.test(o.kind):/máu|tiểu|xét nghiệm|lab|blood|sample/i.test(o.kind));
 const current=orders.find(o=>o.id===selected)||orders[0];
 const run=(type,payload)=>{const r=act(type,{id:p.id,orderId:current.id,...payload});setMessage(r?.ok===false?r.error:'Đã lưu. Kết quả được chuyển tới bác sĩ phụ trách để đọc.');};
 return <div className="card"><h2>{p.name} · {role==='ultrasound'?'Kết quả siêu âm':role==='nurse'?'Thăm dò / thủ thuật / kết quả ngoài':'Mẫu & kết quả xét nghiệm'}</h2><p className="muted">{p.id} · {p.phone} · {p.dob||'Chưa có ngày sinh'}</p>{!current?<p className="empty">Chưa có chỉ định phù hợp. Cần chỉ định được bác sĩ xác nhận để thực hiện.</p>:<><label className="field">Chỉ định<select value={current.id} onChange={e=>{setSelected(e.target.value);setReport('');setFile('');setIdentity(false);}}>{orders.map(o=><option value={o.id} key={o.id}>{o.kind} · {o.status}</option>)}</select></label><div className="toolbar" style={{margin:'16px 0'}}><Status>{current.status}</Status><span className="muted">Bác sĩ phụ trách: {p.doctor}</span></div><label className="field"><span><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)}/> Đã xác minh người bệnh và chỉ định bằng hai thông tin nhận diện</span></label>{role==='lab'&&<div className="toolbar" style={{margin:'16px 0'}}><p className="muted">Tiếp nhận đúng mẫu, đúng người và ghi thời điểm thực tế. Ghi nhận mẫu trước khi lưu kết quả.</p><button className="btn" disabled={!identity||current.status!=='ordered'} onClick={()=>run('sampleReceive',{})}>Ghi nhận đã nhận mẫu</button></div>}<label className="field" style={{marginTop:16}}>{role==='ultrasound'?'Mô tả và kết luận siêu âm':'Kết quả / nhận xét'}<textarea rows="9" value={report} onChange={e=>setReport(e.target.value)} placeholder={role==='ultrasound'?'Ghi mô tả khảo sát và kết luận chuyên môn':'Nhập kết quả từ đơn vị thực hiện; không suy diễn kết quả chưa có'}/></label><label className="field">Tệp kết quả<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]?.name||'')}/></label>{file&&<p className="muted">Đã chọn: {file}. Bản mẫu chỉ lưu tên tệp, chưa tải tệp lên máy chủ.</p>}<div className="toolbar" style={{marginTop:20}}><button className="btn primary" disabled={!identity||!report.trim()||current.status==='draft'||(role==='lab'&&current.status==='ordered')} onClick={()=>run('result',{result:report+(file?`\nTệp tham chiếu: ${file}`:'')})}>{role==='ultrasound'?'Xác nhận & chuyển kết quả':'Lưu kết quả nhận được'}</button><span className="muted">{current.reviewed?'Bác sĩ chính đã đọc':'Chưa được bác sĩ chính đọc'} · {p.released?'Đã phát hành':'Chưa phát hành cho khách'}</span></div>{current.result&&<div className="card" style={{marginTop:20,background:'#f7f9fc'}}><h3>Kết quả đã lưu</h3><p style={{whiteSpace:'pre-wrap'}}>{current.result}</p></div>}</>}{message&&<p role="status">{message}</p>}</div>;
}
export default function Clinical({role}){
 const {data,act}=useClinic();const [query,setQuery]=useState('');const [selected,setSelected]=useState(null);const [filter,setFilter]=useState('all');
 const patients=(data.patients||[]).filter(p=>`${p.name} ${p.phone} ${p.id}`.toLowerCase().includes(query.toLowerCase())).filter(p=>filter==='all'||p.stage===filter);
 const patient=(data.patients||[]).find(p=>p.id===selected)||patients[0];
 return <><div className="toolbar"><div><h1>{labels[role]||'Lâm sàng'}</h1><p className="muted">Danh sách hôm nay · Một hồ sơ xuyên suốt lần khám</p></div><Status>{patients.length} người bệnh</Status></div><div className="toolbar"><input aria-label="Tìm người bệnh" placeholder="Tìm tên, số điện thoại, mã hồ sơ…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Lọc trạng thái" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tất cả trạng thái</option>{Object.entries(stageNames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div><div style={{display:'grid',gridTemplateColumns:'260px minmax(0,1fr)',gap:20,marginTop:20}}><aside className="card" style={{alignSelf:'start',padding:8}}>{patients.map(p=><button className="btn" key={p.id} onClick={()=>setSelected(p.id)} style={{display:'block',width:'100%',textAlign:'left',marginBottom:6,padding:14,borderColor:patient?.id===p.id?'#178a79':'transparent',background:patient?.id===p.id?'#eef8f5':'white'}}><strong>{p.name}</strong><span className="muted" style={{display:'block',marginTop:5}}>{p.time} · {p.service}</span><small>{stageNames[p.stage]||p.status}</small></button>)}{!patients.length&&<p className="empty">Không có người bệnh phù hợp.</p>}</aside><section>{patient?role==='doctor'||role==='scribe'?<ClinicalRecord key={patient.id+role} patient={patient} role={role} data={data} act={act}/>:role==='nurse'?<><Vitals key={patient.id} patient={patient} act={act}/><p className="notice">Dịch vụ bên dưới do người được phân công, đủ chuyên môn thực hiện; điều dưỡng ghi nhận hoặc tiếp nhận kết quả ngoài có căn cứ. Chưa thay thế checklist chuyên môn từng dịch vụ.</p><ServiceResults key={patient.id+'service'} patient={patient} role="nurse" act={act}/></>:<ServiceResults key={patient.id+role} patient={patient} role={role} act={act}/>:<div className="card empty">Chọn người bệnh để bắt đầu làm việc.</div>}</section></div></>;
}
