import React, {useState} from 'react';
import {useClinic} from '../store';

const services=['Phụ khoa','Sản khoa','Nội tiết','Hiếm muộn','Siêu âm','Xét nghiệm','Tái khám'];
const times=['14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30'];
const stageNames={booking:'Có lịch hẹn',waiting:'Chờ phục vụ',vitals:'Đo sinh hiệu',exam:'Đang khám',services:'Thực hiện dịch vụ',review:'Chờ đọc kết quả',checkout:'Chuẩn bị ra về',departed:'Đã ra về'};
const label=p=>p.status==='Đã hủy'?'Đã hủy':p.status==='Rời tạm'?'Rời tạm':stageNames[p.stage]||p.status;
export default function Frontdesk({role}){
 const {data,act}=useClinic();
 const patients=data.patients||[],tasks=data.tasks||[];
 const doctors=[...new Set([...patients.map(p=>p.doctor).filter(d=>d&&d!=='Chưa phân'),'BS Minh','BS Thành'])];
 const [query,setQuery]=useState(''),[tab,setTab]=useState('all'),[selected,setSelected]=useState(null),[dialog,setDialog]=useState(null),[error,setError]=useState(''),[toast,setToast]=useState(''),[result,setResult]=useState(null);
 const [form,setForm]=useState({name:'',phone:'',dob:'',service:services[0],doctor:'BS Minh',time:'16:00',reason:'',outcome:'',pendingOwner:'CSKH',due:''});
 const [chat,setChat]=useState([{from:'ai',text:'Chào bạn, bạn muốn đặt lịch khám hay tìm thông tin về buổi khám? Mình có thể giúp chuẩn bị yêu cầu đặt lịch để bạn kiểm tra trước khi xác nhận.'}]);
 const [message,setMessage]=useState('');
 const patient=patients.find(p=>p.id===selected);
 const open=(kind,p)=>{setDialog(kind);setSelected(p?.id||null);setError('');setForm({name:p?.name||'',phone:p?.phone||'',dob:p?.dob||'',service:p?.service||services[0],doctor:p?.doctor||'BS Minh',time:p?.time||'16:00',reason:'',outcome:'',pendingOwner:'CSKH',due:''});};
 const run=(type,payload)=>{try{const r=act(type,payload);if(r?.ok===false){setError(r.error||'Chưa thể thực hiện. Kiểm tra lại thông tin.');return false;}setError('');setToast('Đã cập nhật dữ liệu. Các bộ phận liên quan cùng nhìn thấy thay đổi.');return true;}catch(e){setError(e.message||'Không thể cập nhật.');return false;}};
 const submit=e=>{e.preventDefault();const kind=dialog;const payload={...form,id:selected,...(kind==='walkin'?{time:'',doctor:''}:{})};if(run(kind,payload)){setDialog(null);if(kind==='book')setResult({...form});}};
 const clean=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
 const rows=patients.filter(p=>clean(`${p.name} ${p.phone} ${p.id}`).includes(clean(query))).filter(p=>tab==='all'||(tab==='booked'&&p.stage==='booking'&&p.status!=='Đã hủy')||(tab==='active'&&!['booking','departed'].includes(p.stage)&&p.status!=='Đã hủy')||(tab==='away'&&p.status==='Rời tạm')||(tab==='done'&&p.stage==='departed'));
 const field=(key,title,type='text')=><label className="field">{title}<input type={type} value={form[key]} required={['name','phone','reason','outcome'].includes(key)} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const bookingFields=<><div className="grid2">{field('name','Họ và tên')}{field('phone','Số điện thoại','tel')}{field('dob','Ngày sinh','date')}<label className="field">Dịch vụ<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{services.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="grid2"><label className="field">Bác sĩ<select value={form.doctor} onChange={e=>setForm({...form,doctor:e.target.value})}>{doctors.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Giờ khám · ngày mô phỏng hôm nay<select value={form.time} onChange={e=>setForm({...form,time:e.target.value})}>{times.map(x=><option key={x}>{x}</option>)}</select></label></div><p className="muted">Cơ sở Kim Ngưu · Lịch và bác sĩ là dữ liệu mẫu. Hệ thống kiểm tra lại chỗ khi xác nhận.</p></>;
 const sendChat=e=>{e.preventDefault();if(!message.trim())return;const m=message.trim();let answer='Bạn có thể chọn dịch vụ, bác sĩ và giờ phù hợp ở phiếu bên cạnh. Mình chưa đặt lịch: bạn cần kiểm tra và bấm Xác nhận đặt lịch.';if(/giờ|mở|thời gian/i.test(m))answer='Buổi khám mẫu: thứ Hai–thứ Sáu chiều/tối; cuối tuần cả ngày. Danh sách bên cạnh đang minh họa các giờ chiều, chưa phải lịch nhân sự thực tế.';if(/đau|máu|sốt|thuốc/i.test(m))answer='Mình ghi nhận nhu cầu của bạn. Trợ lý đặt lịch không đưa ra chẩn đoán hoặc kê thuốc. Hãy trao đổi trực tiếp với nhân viên y tế để được hướng dẫn phù hợp.';setChat([...chat,{from:'you',text:m},{from:'ai',text:answer}]);setMessage('');};
 return <div className="frontdesk-workspace">
 {toast&&<div className="card" role="status" style={{borderLeft:'4px solid #19a88a',marginBottom:16,display:'flex',justifyContent:'space-between'}}>{toast}<button className="btn" onClick={()=>setToast('')}>Đóng</button></div>}
 {error&&!dialog&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}
 {role==='customer'?<>
 <div className="card" style={{background:'linear-gradient(110deg,#e9f5f2,#f7f9fc)',marginBottom:20}}><span className="badge">DR4WOMEN · CHĂM SÓC SỨC KHỎE PHỤ NỮ</span><h2>Chủ động chăm sóc sức khỏe của bạn</h2><p>Chọn lịch khám phù hợp. Đội ngũ phòng khám tiếp nhận và đồng hành cùng bạn.</p></div>
 <div className="grid2"><section className="card"><h3>Đặt lịch tại phòng khám</h3>{result?<><div className="badge">Đã tạo lịch trong sản phẩm mẫu</div><h2>{result.name}</h2><p>{result.service} · {result.doctor}</p><p>Hôm nay, {result.time} · Kim Ngưu</p><p className="muted">Lịch đã xuất hiện trên màn CSKH và lễ tân. Chưa gửi SMS hoặc Zalo thật.</p><button className="btn primary" onClick={()=>setResult(null)}>Đặt một lịch khác</button></>:<form onSubmit={e=>{e.preventDefault();if(run('book',form))setResult({...form});}}>{bookingFields}<button className="btn primary" type="submit">Xác nhận đặt lịch</button></form>}</section><section className="card"><h3>Trợ lý đặt lịch</h3><p className="muted">Hội thoại mô phỏng · chưa kết nối AI thật</p><div style={{minHeight:260,maxHeight:420,overflowY:'auto'}}>{chat.map((x,i)=><div key={i} style={{padding:14,margin:'10px 0',borderRadius:14,background:x.from==='you'?'#eef2ff':'#f3f6f8',marginLeft:x.from==='you'?35:0,marginRight:x.from==='ai'?35:0}}><small className="muted">{x.from==='you'?'Bạn':'Trợ lý'}</small><div>{x.text}</div></div>)}</div><form className="toolbar" onSubmit={sendChat}><input aria-label="Tin nhắn cho trợ lý" placeholder="Tôi muốn đặt lịch khám…" value={message} onChange={e=>setMessage(e.target.value)} style={{flex:1}}/><button className="btn primary">Gửi</button></form></section></div>
 </>:<>
 <div className="grid3" style={{marginBottom:20}}><div className="card"><div className="muted">Lịch hẹn hôm nay</div><strong className="metric">{patients.filter(p=>p.stage==='booking'&&p.status!=='Đã hủy').length}</strong></div><div className="card"><div className="muted">Lượt đang phục vụ</div><strong className="metric">{patients.filter(p=>!['booking','departed'].includes(p.stage)&&p.status!=='Đã hủy').length}</strong></div><div className="card"><div className="muted">{role==='cskh'?'Việc liên hệ chưa hoàn tất':'Đã kết thúc lượt'}</div><strong className="metric">{role==='cskh'?tasks.filter(t=>t.status!=='done'&&t.status!=='completed').length:patients.filter(p=>p.stage==='departed').length}</strong></div></div>
 <section className="card"><div className="toolbar" style={{justifyContent:'space-between'}}><div><h3>{role==='cskh'?'Khách hàng & lịch hẹn':'Tiếp đón & hành trình hôm nay'}</h3><p className="muted">Kim Ngưu · một cơ sở · quy mô dự kiến 100 khách/ngày</p></div><button className="btn primary" onClick={()=>open(role==='cskh'?'book':'walkin')}>{role==='cskh'?'+ Đặt lịch':'+ Khách vãng lai'}</button></div><div className="toolbar"><input aria-label="Tìm khách" placeholder="Tìm tên, số điện thoại, mã hồ sơ…" value={query} onChange={e=>setQuery(e.target.value)} style={{minWidth:280}}/><div className="tabs">{[['all','Tất cả'],['booked','Chưa đến'],['active','Đang phục vụ'],['away','Rời tạm'],['done','Đã ra về']].map(([v,t])=><button className={`btn ${tab===v?'active':''}`} key={v} onClick={()=>setTab(v)}>{t}</button>)}</div></div>
 <div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Khách hàng</th><th>Lịch / dịch vụ</th><th>Bác sĩ</th><th>Hành trình</th><th>Thao tác</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><button className="btn" onClick={()=>{setSelected(p.id);setDialog('detail');}}><strong>{p.name}</strong></button><div className="muted">{p.phone} · {p.id}</div></td><td><strong>{p.time||'Vãng lai'}</strong><div>{p.service}</div></td><td>{p.doctor||'Chưa phân công'}</td><td><span className="badge">{label(p)}</span></td><td><div className="toolbar">{role==='cskh'?<><button className="btn" disabled={p.stage!=='booking'||p.status==='Đã hủy'} title="Chỉ đổi lịch chưa tiếp nhận" onClick={()=>open('reschedule',p)}>Đổi lịch</button><button className="btn" onClick={()=>open('contact',p)}>Liên hệ</button><button className="btn danger" disabled={p.stage!=='booking'||p.status==='Đã hủy'} onClick={()=>open('cancel',p)}>Hủy</button></>:<>{p.stage==='booking'&&p.status!=='Đã hủy'?<button className="btn primary" onClick={()=>open('verify',p)}>Tiếp nhận</button>:p.status==='Rời tạm'?<button className="btn primary" onClick={()=>run('return',{id:p.id})}>Đã quay lại</button>:!['departed','booking'].includes(p.stage)&&<button className="btn" onClick={()=>run('away',{id:p.id})}>Rời tạm</button>}<button className="btn" disabled={['booking','departed'].includes(p.stage)||p.status==='Đã hủy'} onClick={()=>open('checkout',p)}>Kết thúc lượt</button></>}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Không có hồ sơ phù hợp bộ lọc.</p>}</div></section>
 {role==='cskh'&&<section className="card" style={{marginTop:20}}><h3>Việc cần liên hệ</h3><p className="muted">Mỗi việc có người phụ trách, hạn và kết quả xử lý.</p>{tasks.length?<table className="table"><thead><tr><th>Khách / công việc</th><th>Phụ trách</th><th>Hạn</th><th>Trạng thái</th><th></th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><strong>{patients.find(p=>p.id===t.patientId)?.name||'Khách hàng'}</strong><div>{t.label}</div></td><td>{t.owner}</td><td>{t.due||'Chưa ấn định'}</td><td>{t.status==='done'?'Đã hoàn tất':t.status==='open'?'Đang mở':t.status}</td><td><button className="btn" disabled={['done','completed'].includes(t.status)} onClick={()=>{open('completeTask');setSelected(t.id);}}>Ghi kết quả</button></td></tr>)}</tbody></table>:<p className="empty">Chưa có công việc liên hệ.</p>}</section>}
 </>}
 {dialog&&<div className="modal-backdrop" onClick={()=>setDialog(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Thao tác khách hàng" onClick={e=>e.stopPropagation()} style={{maxWidth:660,width:'min(660px,94vw)',maxHeight:'90vh',overflowY:'auto'}}><div className="toolbar" style={{justifyContent:'space-between'}}><h3>{({book:'Tạo lịch hẹn',walkin:'Tiếp nhận khách vãng lai',reschedule:'Đổi lịch hẹn',cancel:'Hủy lịch hẹn',contact:'Ghi nhận liên hệ',checkout:'Kiểm tra trước khi ra về',verify:'Xác minh đúng người bệnh',detail:'Hồ sơ & tiến trình',completeTask:'Kết quả công việc'})[dialog]}</h3><button className="btn" onClick={()=>setDialog(null)}>Đóng</button></div>{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}
 {dialog==='detail'?<><h2>{patient?.name}</h2><p>{patient?.phone} · Ngày sinh: {patient?.dob||'Chưa bổ sung'}</p><p>{patient?.service} · {patient?.doctor}</p><span className="badge">{patient&&label(patient)}</span><h4>Dịch vụ trong lượt</h4>{patient?.orders?.length?patient.orders.map((o,i)=><p key={o.id||i}>{o.kind||o.name||o.service||o.type} · {o.status}</p>):<p className="muted">Chưa có chỉ định.</p>}<h4>Thanh toán</h4><p>{Number(patient?.total||0).toLocaleString('vi-VN')} đ · {Number(patient?.paid||0)>=Number(patient?.total||0)?'Đã thanh toán đủ':`Đã thu ${Number(patient?.paid||0).toLocaleString('vi-VN')} đ`}</p><h4>Ghi chú</h4><p>{patient?.note||'Chưa có ghi chú.'}</p></>:dialog==='verify'?<><p>Đối chiếu trực tiếp ít nhất hai thông tin trước khi tiếp nhận. Không xác minh chỉ bằng số điện thoại dùng chung.</p><div className="card"><strong>{patient?.name}</strong><p>{patient?.phone} · Ngày sinh: {patient?.dob||'Chưa có — cần hỏi bổ sung'}</p><p>{patient?.service} · {patient?.time}</p></div><button className="btn primary" onClick={()=>{if(run('checkin',{id:selected}))setDialog(null);}}>Đã đối chiếu đúng người · Tiếp nhận</button></>:<form onSubmit={submit}>{dialog==='book'?bookingFields:dialog==='walkin'?<><div className="grid2">{field('name','Họ và tên')}{field('phone','Số điện thoại','tel')}{field('dob','Ngày sinh','date')}<label className="field">Dịch vụ<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{services.map(x=><option key={x}>{x}</option>)}</select></label></div><p className="muted">Tạo lượt tiếp nhận thực tế, không tạo giờ hẹn giả. Bác sĩ được phân công trong quá trình điều phối.</p></>:dialog==='reschedule'?<div className="grid2">{field('time','Giờ mới','time')}{field('doctor','Bác sĩ')}</div>:dialog==='cancel'?field('reason','Lý do hủy'):dialog==='checkout'?<><p>Kiểm tra các dịch vụ, kế hoạch theo dõi và khoản cần thanh toán. Kết quả chưa về phải có người theo dõi.</p>{field('reason','Ghi chú ra về / việc còn chờ')}{field('pendingOwner','Người phụ trách kết quả còn chờ')}</>:<>{field('outcome','Kết quả liên hệ / xử lý')}{dialog==='contact'&&field('due','Hạn liên hệ tiếp (nếu cần)','datetime-local')}</>}<div className="toolbar" style={{marginTop:20}}><button className="btn" type="button" onClick={()=>setDialog(null)}>Quay lại</button><button className={`btn ${dialog==='cancel'?'danger':'primary'}`} type="submit">{dialog==='book'?'Kiểm tra & đặt lịch':dialog==='walkin'?'Tạo lượt vãng lai':dialog==='checkout'?'Xác nhận kết thúc lượt':'Lưu xác nhận'}</button></div></form>}
 </section></div>}
 </div>;
}
