export const roles={customer:'Khách hàng',cskh:'CSKH',reception:'Lễ tân',nurse:'Điều dưỡng',scribe:'Thư ký y khoa',doctor:'Bác sĩ',ultrasound:'Siêu âm',lab:'Xét nghiệm',lead:'Trưởng ca',pharmacy:'Kho & phát thuốc',cashier:'Thu ngân',admin:'Quản trị'};
const patient=(id,name,time,stage,extra={})=>({id,name,phone:'09000000'+id.slice(1),dob:'1992-05-18',service:'Phụ khoa',doctor:'BS Minh',time,status:'Đã đặt',stage,note:'Lý do khám: Khám định kỳ (dữ liệu mẫu).\nNhận định và kế hoạch: chờ bác sĩ xác nhận.',version:1,approvedVersion:0,released:false,vitals:null,orders:[],prescription:[],paid:0,total:350000,...extra});
export function seed(){return{revision:0,patients:[patient('P01','Nguyễn Lan · mẫu','17:30','booking'),patient('P02','Trần Hương · mẫu','17:45','waiting',{status:'Đã tiếp nhận'}),patient('P03','Lê Mai · mẫu','18:00','exam',{status:'Đang khám',vitals:{bp:'118/76',weight:'54',height:'160'}}),patient('P04','Phạm An · mẫu','18:15','services',{approvedVersion:1,status:'Chờ xét nghiệm',orders:[{id:'O04',kind:'Xét nghiệm máu',status:'sampled',result:'',reviewed:false}]}),patient('P05','Hoàng Thu · mẫu','18:30','checkout',{approvedVersion:1,released:true,status:'Chờ thanh toán',prescription:[{drugId:'D01',quantity:2,dispensed:0,approvedVersion:1}],orders:[{id:'O05',kind:'Siêu âm',status:'received',result:'Báo cáo mẫu đã được kiểm tra.',reviewed:true}]}),patient('P06','Vũ Hà · mẫu','18:45','departed',{status:'Chờ kết quả sau về',approvedVersion:1,departurePlan:true,orders:[{id:'O06',kind:'Xét nghiệm ngoài',status:'sampled',result:'',reviewed:false}]})],drugs:[{id:'D01',name:'Dược phẩm mẫu A',unit:'hộp',lot:'LOT-2608',expiry:'2027-08-31',stock:24,price:45000},{id:'D02',name:'Dược phẩm mẫu B',unit:'hộp',lot:'LOT-2609',expiry:'2027-09-30',stock:8,price:80000},{id:'D03',name:'Dược phẩm mẫu C',unit:'lọ',lot:'LOT-2501',expiry:'2026-01-31',stock:2,price:60000}],tasks:[{id:'T01',patientId:'P01',label:'Xác nhận lịch khám',owner:'CSKH',due:'Hôm nay 16:30',status:'open'},{id:'T06',patientId:'P06',label:'Theo dõi kết quả xét nghiệm ngoài',owner:'CSKH',due:'Ngày mai 10:00',status:'open'}],payments:[],events:[],observations:[],movements:[],settings:{capacity:4,clinic:'ClinicAI · Cơ sở 01',source:'Notion',iotEnabled:false},sync:[{id:'S01',source:'Notion',label:'Hồ sơ trùng số liên hệ',status:'needs_review'},{id:'S02',source:'Google Sheet',label:'Lịch thiếu mã bác sĩ',status:'needs_review'}],users:Object.entries(roles).filter(([r])=>r!=='customer').map(([id,name])=>({id,name,active:true})),notifications:[]};}
const rights={book:['customer','cskh'],walkin:['reception'],reschedule:['cskh','reception'],cancel:['cskh','reception'],contact:['cskh','reception'],completeTask:['cskh','lead'],checkin:['reception'],away:['reception'],return:['reception'],checkout:['reception'],vitals:['nurse'],startExam:['doctor','scribe'],saveNote:['doctor','scribe'],approve:['doctor'],release:['doctor'],order:['doctor'],prescribe:['doctor'],draftOrder:['doctor','scribe'],draftPrescribe:['doctor','scribe'],sampleReceive:['lab'],result:['lab','ultrasound','nurse'],reviewResult:['doctor'],dispense:['pharmacy'],stock:['pharmacy'],payment:['cashier'],webhook:['cashier'],refund:['cashier'],assign:['lead'],iot:['lead'],route:['lead'],resolveSync:['admin'],settings:['admin'],toggleUser:['admin']};
export function command(data,type,a,role){
 const fail=error=>({ok:false,error,data});if(!(rights[type]||[]).includes(role))return fail('Vai trò này không được thực hiện thao tác.');
 const d=structuredClone(data),p=d.patients.find(x=>x.id===a.id),uid=prefix=>prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);
 const event=(name,detail={})=>d.events.unshift({id:uid('E'),name,type:name,patientId:a.id||null,actor:roles[role],time:new Date().toLocaleTimeString('vi-VN'),detail});
 const task=(label,owner,due)=>d.tasks.push({id:uid('T'),patientId:a.id,label,owner,due,status:'open'});
 const needPatient=!['book','walkin','assign','stock','webhook','refund','settings','resolveSync','toggleUser','completeTask'].includes(type);if(needPatient&&!p)return fail('Không tìm thấy người bệnh.');
 const needVersion=()=>p.approvedVersion>0&&p.approvedVersion===p.version;
 switch(type){
 case'book':case'walkin':{
 if(!a.name?.trim()||!/^\d{9,11}$/.test((a.phone||'').replace(/\s/g,'')))return fail('Nhập tên và số liên hệ hợp lệ (9–11 chữ số).');
 if(type==='book'&&(!a.time||!a.doctor||!a.service))return fail('Chọn dịch vụ, bác sĩ và giờ khám.');
 if(type==='book'&&d.patients.filter(x=>x.time===a.time&&x.doctor===a.doctor&&x.status!=='Đã hủy').length>=d.settings.capacity)return fail('Khung giờ đã đầy theo chính sách demo. Hãy chọn giờ khác.');
 const id=uid('P');d.patients.unshift(patient(id,a.name,a.time||'Vãng lai',type==='book'?'booking':'waiting',{phone:a.phone,dob:a.dob||'',service:a.service||'Phụ khoa',doctor:a.doctor||'Chưa phân',status:type==='book'?'Đã đặt':'Đã tiếp nhận'}));a={...a,id};task(type==='book'?'Xác nhận lịch khám':'Đo sinh hiệu',type==='book'?'CSKH':'Điều dưỡng','Trong ca');event(type==='book'?'AppointmentCreated':'PatientCheckedIn');break;}
 case'reschedule':if(p.stage!=='booking')return fail('Chỉ đổi lịch chưa tiếp nhận.');if(!a.time)return fail('Chọn giờ mới.');if(d.patients.filter(x=>x.id!==p.id&&x.time===a.time&&x.doctor===(a.doctor||p.doctor)&&x.status!=='Đã hủy').length>=d.settings.capacity)return fail('Giờ mới đầy. Lịch cũ vẫn giữ.');p.time=a.time;p.doctor=a.doctor||p.doctor;event('AppointmentRescheduled');break;
 case'cancel':if(p.stage!=='booking'||!a.reason?.trim())return fail('Chỉ hủy lịch chưa tiếp nhận, cần lý do.');p.status='Đã hủy';task('Gọi lại sau hủy: '+a.reason,'CSKH','Trong 1–14 ngày · cần chọn hạn');event('AppointmentCancelled');break;
 case'contact':if(!a.outcome)return fail('Chọn kết quả liên hệ.');p.contactOutcome=a.outcome;task('Theo dõi liên hệ: '+a.outcome,'CSKH',a.due||'Ngày mai');event('ContactOutcomeRecorded',{outcome:a.outcome});break;
 case'completeTask':{let t=d.tasks.find(t=>t.id===a.id);if(!t||!a.outcome?.trim())return fail('Cần việc và kết quả xử lý.');t.status='done';t.outcome=a.outcome;event('WorkCompleted');break;}
 case'checkin':if(p.stage!=='booking'||p.status==='Đã hủy')return fail('Lịch đã tiếp nhận hoặc bị hủy.');p.stage='waiting';p.status='Đã tiếp nhận';p.arrivedAt=new Date().toISOString();task('Đo sinh hiệu','Điều dưỡng','Trong ca');event('PatientCheckedIn');break;
 case'away':if(['booking','departed'].includes(p.stage))return fail('Người bệnh chưa ở hàng chờ.');p.previousStage=p.stage;p.status='Rời tạm';event('PatientTemporarilyAway');break;
 case'return':if(p.status!=='Rời tạm')return fail('Không có ghi nhận rời tạm.');p.status='Đã quay lại';p.stage=p.previousStage||'waiting';event('PatientReturned');break;
 case'vitals':if(['booking','departed'].includes(p.stage))return fail('Cần lượt đã tiếp nhận.');if(!a.values?.bp&&(!a.values?.systolic||!a.values?.diastolic))return fail('Cần số đo huyết áp.');p.vitals={...a.values,bp:a.values.bp||a.values.systolic+'/'+a.values.diastolic};p.stage='exam';p.status='Chờ bác sĩ';event('VitalsRecorded');break;
 case'startExam':if(!p.vitals)return fail('Chưa có sinh hiệu bắt buộc trong tuyến demo.');p.stage='exam';p.status='Đang khám';event('ConsultationStarted');break;
 case'saveNote':if(!['exam','services','review','checkout'].includes(p.stage))return fail('Lượt chưa ở giai đoạn ghi hồ sơ.');if(a.expectedVersion!==p.version)return fail('Hồ sơ đã thay đổi; tải lại trước khi lưu.');if(!a.note?.trim())return fail('Nội dung đang trống.');p.noteHistory=[...(p.noteHistory||[]),{version:p.version,note:p.note,approved:p.approvedVersion===p.version}];p.note=a.note;p.version++;p.released=false;event('ClinicalDraftSaved',{version:p.version,enteredBy:roles[role],clinician:p.doctor});break;
 case'approve':if(a.expectedVersion!==p.version)return fail('Có bản mới do người khác sửa. Đọc lại trước khi xác nhận.');if(p.orders.some(o=>o.status==='draft')){p.stage='services';p.status='Chờ thực hiện dịch vụ';p.orders.filter(o=>o.status==='draft').forEach(o=>task('Thực hiện '+o.kind,o.kind.includes('Siêu')?'Siêu âm':/máu|tiểu|xét nghiệm/i.test(o.kind)?'Xét nghiệm':'Điều dưỡng / người được phân công','Trong ca'));}p.approvedVersion=p.version;p.departurePlan=true;p.orders=p.orders.map(o=>o.status==='draft'?{...o,status:'ordered'}:o);p.prescription=p.prescription.map(x=>({...x,approvedVersion:p.version,status:'authorized'}));event('ClinicalVersionApproved',{version:p.version});break;
 case'release':if(!needVersion())return fail('Bác sĩ chưa duyệt phiên bản hiện hành.');if(p.orders.some(o=>!o.reviewed))return fail('Còn kết quả chưa được bác sĩ kiểm.');p.released=true;p.stage=p.stage==='departed'?'departed':'checkout';task('Gửi kết quả được phép phát hành','CSKH','Trong ca');event('ReportReleased');break;
 case'draftOrder':if(!a.kind||p.orders.some(o=>o.kind===a.kind))return fail('Chọn dịch vụ mới, không tạo trùng chỉ định.');if(!p.vitals)return fail('Cần lượt đã vào khám.');p.version++;p.released=false;p.orders.push({id:uid('O'),kind:a.kind,status:'draft',result:'',reviewed:false,enteredBy:roles[role]});event('OrderDraftSaved',{version:p.version});break;
 case'draftPrescribe':if(!d.drugs.some(x=>x.id===a.drugId)||!Number.isInteger(a.quantity)||a.quantity<=0)return fail('Chọn thuốc và số lượng hợp lệ.');if(p.prescription.some(x=>x.drugId===a.drugId))return fail('Thuốc đã có trong bản đơn.');if(!p.vitals)return fail('Cần lượt đã vào khám.');p.version++;p.released=false;p.prescription.push({drugId:a.drugId,quantity:a.quantity,dispensed:0,approvedVersion:0,status:'draft',enteredBy:roles[role]});event('PrescriptionDraftSaved',{version:p.version});break;
 case'order':if(!needVersion())return fail('Cần bác sĩ xác nhận hồ sơ hiện hành.');if(!a.kind)return fail('Chọn dịch vụ.');p.orders.push({id:uid('O'),kind:a.kind,status:'ordered',result:'',reviewed:false});p.stage='services';p.released=false;task('Thực hiện '+a.kind,a.kind.includes('Siêu')?'Siêu âm':'Xét nghiệm','Trong ca');event('OrderAuthorized');break;
 case'sampleReceive':{let o=p.orders.find(o=>o.id===a.orderId);if(!o||o.status!=='ordered')return fail('Không có chỉ định chờ lấy mẫu.');o.status='sampled';event('SampleCollected');break;}
 case'result':{let o=p.orders.find(o=>o.id===a.orderId);if(!o||o.status==='draft'||!a.result?.trim())return fail('Chọn đúng chỉ định và nhập kết quả.');o.status='received';o.result=a.result;o.reviewed=false;p.released=false;p.stage=p.stage==='departed'?'departed':'review';task('Bác sĩ đọc '+o.kind,'Bác sĩ','Trong ca');event('ResultReceived');break;}
 case'reviewResult':{let o=p.orders.find(o=>o.id===a.orderId);if(!o||o.status!=='received')return fail('Chưa có kết quả để đọc.');o.reviewed=true;event('ResultReviewed');break;}
 case'prescribe':if(!needVersion())return fail('Cần bác sĩ duyệt hồ sơ hiện hành.');if(!d.drugs.some(x=>x.id===a.drugId)||!Number.isInteger(a.quantity)||a.quantity<=0)return fail('Chọn thuốc và số lượng hợp lệ.');if(p.prescription.some(x=>x.drugId===a.drugId))return fail('Thuốc đã có trong đơn demo; không cộng trùng.');p.prescription.push({drugId:a.drugId,quantity:a.quantity,dispensed:0,approvedVersion:p.version});event('PrescriptionAuthorized');break;
 case'dispense':{let drug=d.drugs.find(x=>x.id===a.drugId),line=p.prescription.find(x=>x.drugId===a.drugId);if(!drug||!line||line.approvedVersion!==p.approvedVersion||!needVersion())return fail('Không có dòng đơn thuốc đã được bác sĩ duyệt còn hiệu lực.');if(!Number.isInteger(a.quantity)||a.quantity<1||a.quantity>drug.stock||a.quantity>line.quantity-line.dispensed)return fail('Số cấp vượt tồn hoặc số còn được cấp trong đơn.');if(drug.expiry<'2026-09-08')return fail('Lô đã hết hạn.');drug.stock-=a.quantity;line.dispensed+=a.quantity;d.movements.unshift({id:uid('M'),drugId:a.drugId,quantity:-a.quantity,reason:'Cấp cho '+p.name,time:new Date().toISOString()});event('MedicationDispensed');break;}
 case'stock':{let drug=d.drugs.find(x=>x.id===a.drugId);if(!drug||!Number.isInteger(a.quantity)||!a.quantity||!a.reason?.trim()||drug.stock+a.quantity<0)return fail('Cần số lượng hợp lệ và lý do; không để âm tồn.');drug.stock+=a.quantity;d.movements.unshift({id:uid('M'),drugId:a.drugId,quantity:a.quantity,reason:a.reason,time:new Date().toISOString()});event('InventoryAdjusted');break;}
 case'payment':if(!Number.isInteger(a.amount)||a.amount<=0||a.amount>p.total-p.paid)return fail('Số tiền phải dương và không vượt khoản còn phải thu.');if(d.payments.some(x=>x.patientId===p.id&&x.status==='pending'))return fail('Đang có yêu cầu thanh toán chờ xử lý.');{let pay={id:uid('PAY'),patientId:p.id,amount:a.amount,status:a.method==='cash'?'paid':'pending',method:a.method,reference:uid('REF'),refunded:0};d.payments.unshift(pay);if(pay.status==='paid')p.paid+=pay.amount;event(pay.status==='paid'?'PaymentRecorded':'PaymentRequested');}break;
 case'webhook':{let pay=d.payments.find(x=>x.id===a.paymentId);if(!pay||a.signatureValid!==true||a.amount!==pay.amount||a.reference!==pay.reference)return fail('Thông báo chưa được xác thực hoặc sai tiền/mã tham chiếu.');if(pay.status==='paid')return{ok:true,data,message:'Đã ghi nhận trước đó; không thu lặp.'};if(pay.status!=='pending')return fail('Giao dịch không còn chờ thanh toán.');pay.status='paid';d.patients.find(x=>x.id===pay.patientId).paid+=pay.amount;event('PaymentRecorded',{paymentId:pay.id});break;}
 case'refund':{let pay=d.payments.find(x=>x.id===a.paymentId);if(!pay||pay.status!=='paid'||!Number.isInteger(a.amount)||a.amount<=0||a.amount>pay.amount-pay.refunded||!a.reason?.trim())return fail('Cần giao dịch đã thu, số hoàn hợp lệ và lý do.');pay.refunded+=a.amount;d.patients.find(x=>x.id===pay.patientId).paid-=a.amount;event('PaymentRefunded',{paymentId:pay.id,amount:a.amount,reason:a.reason});break;}
 case'checkout':if(['booking','waiting'].includes(p.stage)||!p.departurePlan||!needVersion())return fail('Cần phương án chuyên môn được bác sĩ xác nhận trước ra về.');if(p.stage==='departed')return fail('Đã ghi nhận ra về.');if((p.orders.some(o=>!o.reviewed)||p.paid<p.total||p.prescription.some(x=>x.dispensed<x.quantity))&&(!a.pendingOwner||!a.reason))return fail('Còn nghĩa vụ: nhập phương án và người theo dõi.');if(a.pendingOwner)task('Theo dõi sau về: '+a.reason,a.pendingOwner,a.due||'Ngày mai 10:00 · hạn demo');p.stage='departed';p.status='Đã ra về';event('PatientDeparted');break;
 case'assign':{let t=d.tasks.find(x=>x.id===a.taskId);if(!t||!a.owner||!a.due)return fail('Chọn người nhận và hạn.');t.owner=a.owner;t.due=a.due;t.status='open';event('WorkAssigned');break;}
 case'iot':d.observations.unshift({id:uid('LOC'),patientId:p.id,name:p.name,zone:a.zone||'Sảnh chờ',time:new Date().toLocaleTimeString('vi-VN'),confidence:0.78});event('LocationObserved');break;
 case'route':if(!a.reason?.trim())return fail('Cần lý do điều phối.');if(!['waiting','vitals','exam','services','review'].includes(a.stage)||p.stage==='booking'||p.stage==='departed')return fail('Chỉ điều phối các bước đang phục vụ.');p.stage=a.stage;p.status='Đã điều phối';event('WorkRerouted',{reason:a.reason});break;
 case'resolveSync':{let s=d.sync.find(x=>x.id===a.id);if(!s)return fail('Không có bản nguồn.');s.status='reviewed';event('SourceReviewRecorded');break;}
 case'settings':if(a.capacity!==undefined&&(!Number.isInteger(a.capacity)||a.capacity<1))return fail('Sức chứa demo phải dương.');d.settings={...d.settings,...a};event('SettingsUpdated');break;
 case'toggleUser':{let u=d.users.find(x=>x.id===a.id);if(!u)return fail('Không có tài khoản.');u.active=!u.active;event('UserAccessChanged');break;}
 default:return fail('Thao tác chưa được mô phỏng.');
 }
 return{ok:true,data:{...d,revision:d.revision+1},message:'Đã lưu thay đổi'};
}
