# Load static definitions on boot (queues, exchanges, bindings)
load_definitions = /etc/rabbitmq/definitions.json

# Disk free limit (warning when disk < 1GB)
disk_free_limit.absolute = 1GB

# Connection limits dev
channel_max = 128
heartbeat = 60

# Logging
log.console = true
log.console.level = info
