-- Danh mục thuốc CHUẨN theo KiotViet của phòng khám (Tuyền 25/09/2026: "giá
-- thuốc cứ nhìn đây mà làm; chỉ cần fill đủ giá, tên thuốc, hướng dẫn sử dụng
-- đầy đủ, còn lô thuốc, ngày nhập xuất, kho để họ tự fill").
--
-- NGUỒN (đều của phòng khám):
--   * Tên, mã hàng, giá bán, đơn vị bán — `DanhSachSanPham_KV21092026-183746`
--     (xuất KiotViet 21/09): 82 mặt hàng (45 thuốc + 37 hàng hoá).
--   * Cách dùng, lưu ý, đường dùng, biệt dược — phiếu kê đơn v5 (73 dòng,
--     `phieu_kham/dinh_nghia/tham_chieu_nguon.json` mau_thuoc); mặt hàng không
--     có trên phiếu lấy "Liều tham khảo" của Notion lib 6 nếu có.
--   * 9 thuốc có trên phiếu mà KiotViet không bán (Estrogel, Follitrope, Gonal-F,
--     Letrozole, Mensterona, Difavon, Diflucan, Zolmed, Cumlaude kem bôi): giữ
--     giá phiếu, đánh dấu CẦN SOÁT — dược sĩ quyết có nhập về không.
--   KiotViet không có hướng dẫn sử dụng; 12 mặt hàng chưa có nguồn nào (Ozempic,
--   Indole, dụng cụ đo đường huyết…) để trống — dược sĩ điền ở Kho thuốc.
--   Lô, hạn dùng, tồn, ngày nhập/xuất KHÔNG nạp: nhà thuốc tự nhập ở Kho thuốc.
--
-- MỘT NGUỒN GIÁ (khép HOLD J5): hoá đơn thuốc đọc giá ở CẢ `drug_catalog` và
-- `service_price` nhóm thuốc — lệch nhau là quầy không thu được. Giá chuẩn từ
-- nay ở danh mục kho; các dòng `service_price` nhóm thuốc cũ TẮT (không xoá).
--
-- LÀM GÌ (theo từng phòng khám đang có danh mục thuốc):
--   * mỗi mặt hàng chuẩn: tìm dòng cũ trùng tên KiotViet hoặc trùng nhãn phiếu
--     (bỏ qua hoa/thường, dấu cách) → giữ dòng ấy, đặt tên/giá/hướng dẫn chuẩn;
--     chưa có → thêm;
--   * dòng không ứng với mặt hàng chuẩn nào → TẮT (`is_active = false`), không
--     xoá: đơn cũ còn trỏ tới, bật lại được ở Kho thuốc.
-- Gói trong MỘT hàm: migration gọi một lần, seed.sql gọi lại (DB dựng mới).
-- Chạy lại được.

ALTER TABLE public.drug_catalog
    ADD COLUMN IF NOT EXISTS ma_hang    text,
    ADD COLUMN IF NOT EXISTS don_vi_ban text,
    ADD COLUMN IF NOT EXISTS duong_dung text,
    ADD COLUMN IF NOT EXISTS cach_dung  text,
    ADD COLUMN IF NOT EXISTS luu_y      text,
    ADD COLUMN IF NOT EXISTS biet_duoc  text;

COMMENT ON COLUMN public.drug_catalog.don_vi_ban IS
'Đơn vị của unit_price (hộp / viên / ống…). Giá bán MỘT đơn vị này.';
COMMENT ON COLUMN public.drug_catalog.cach_dung IS
'Hướng dẫn sử dụng mặc định — điền sẵn vào đơn khi bác sĩ chọn thuốc.';

CREATE OR REPLACE FUNCTION public.chuan_hoa_danh_muc_thuoc_kiotviet()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  c record;
  r record;
  chon uuid[];
  id_co uuid;
BEGIN
  FOR c IN SELECT DISTINCT d.clinic_id AS id FROM public.drug_catalog d LOOP
    chon := ARRAY[]::uuid[];
    FOR r IN
      SELECT * FROM (VALUES
      ('Aktiv isoflavon', 'SP000102', 410000, 'hộp 30 viên',
       'Uống',
       'Ngày uống 1 viên sau ăn sáng hoặc trưa cùng với lượng nước vừa đủ.',
       'Estrogen thảo dược (Phytoestrogen) giúp giảm bốc hỏa, cải thiện tâm trạng và làn da phụ nữ.',
       'Aktiv Meno / Doppelherz Isoflavone', false,
       ARRAY['aktivisoflavon', 'isoflavon']::text[]),
      ('Androgel', 'SP000059', 85000, 'gói',
       'Bôi ngoài da',
       'Cách ngày bôi 1 lần, mỗi lần 1/3 gói (hoặc 1 pump). Bôi vào vùng da mỏng như xương quai xanh, mặt trong cánh tay hoặc đùi.',
       'Không bôi vào vùng sinh dục nữ. Với nam giới: Bôi 1 gói/ngày vào vùng vai, cánh tay hoặc bụng buổi sáng.',
       'Androgel 50mg / pump', false,
       ARRAY['androgel']::text[]),
      ('Androgel pump', 'SP000130', 2400000, 'lọ',
       NULL,
       'Cách ngày bôi 1 lần, mỗi lần bôi 1/3 gói. Bôi xương quai xanh.  Hoặc vợ bôi cho chồng, mỗi lần dùng 1 gói',
       NULL,
       NULL, false,
       ARRAY['androgelpump']::text[]),
      ('Aspilet', 'SP000115', 1000, 'viên',
       'Uống',
       'Ngày uống duy nhất 1 viên vào buổi tối sau bữa ăn no trước khi đi ngủ.',
       'Dự phòng tiền sản giật, hội chứng kháng phospholipid (APS), tăng tưới máu bánh nhau.',
       'Aspilet 80mg / Aspirin pH8', false,
       ARRAY['aspilet', 'aspilete']::text[]),
      ('Assimicin', 'SP000049', 170000, 'hộp',
       'Uống',
       'Uống 1 lần duy nhất 2 viên (1g) hoặc uống 1 viên/ngày x 3 - 6 ngày liên tục sau ăn no.',
       'Đặc trị Chlamydia, Ureaplasma, Mycoplasma. Nên điều trị đồng thời cho bạn tình.',
       'Assimicin (Azithromycin 500mg / 250mg)', false,
       ARRAY['assicin(3/6/9v)', 'assimicin']::text[]),
      ('Benate fort oinment', 'SP000018', 50000, 'hộp',
       'Bôi ngoài da',
       'Bôi một lớp rất mỏng lên vùng tổn thương âm hộ 1 lần vào buổi tối trong 7-14 ngày.',
       'Đặc trị Lichen xơ hóa teo (Lichen sclerosus), ngứa âm hộ mạn tính. Không bôi sâu vào trong âm đạo.',
       'Benate Fort Ointment (Clobetasol propionate)', false,
       ARRAY['benatefortoinment', 'bennatfort(clobetasol)']::text[]),
      ('Besuto gold mama', 'SP000094', 750000, 'hộp',
       'Uống',
       'Ngày uống 1 viên sau bữa ăn sáng 30 phút cùng nhiều nước.',
       'Bổ sung đa vi chất, vitamin và khoáng chất toàn diện cho thai kỳ và mẹ sau sinh.',
       'Besuto Mama Gold', false,
       ARRAY['besuto', 'besutogoldmama']::text[]),
      ('Betmiga 50mg', 'SP000087', 35000, 'viên',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên vào buổi sáng. Uống nguyên viên với nhiều nước, không nhai hoặc nghiền nát.',
       'Điều trị bàng quang tăng hoạt, tiểu gấp, tiểu nhiều lần, són tiểu gấp.',
       'Betmiga 50mg (Mirabegron)', false,
       ARRAY['betmiga', 'betmiga50mg']::text[]),
      ('Canesten cream 20g', 'SP000046', 55000, 'tuýp',
       'Bôi ngoài da',
       'Ngày bôi 2 lần (sáng - tối), mỗi lần lấy lượng bằng hạt đỗ xanh bôi môi lớn, môi bé, tiền đình.',
       'Đặc trị nấm Candida sinh dục ngoài, chống ngứa rát vùng kín.',
       'Canesten Cream 1% (Clotrimazole)', false,
       ARRAY['canesten', 'canestencream20g']::text[]),
      ('Cavidagel', 'SP000036', 400000, 'hộp',
       'Bôi tại chỗ',
       'Ngày bôi 2 lần, mỗi lần bôi 1 lớp mỏng đều vào vùng tổn thương tiền đình, âm hộ sau khi vệ sinh sạch sẽ.',
       'Thúc đẩy làm lành niêm mạc sau thủ thuật soi, nong tách bao quy đầu âm vật, laser trẻ hóa.',
       'Cavidagel', false,
       ARRAY['cavidagel']::text[]),
      ('Cefnirvid 300 (cefdinir)', 'SP000004', 10000, 'viên',
       'Uống',
       'Ngày uống 2 lần, mỗi lần 1 viên sau ăn sáng và tối. Đợt dùng 5 - 7 ngày.',
       'Kháng sinh nhóm Cephalosporin thế hệ 3 điều trị nhiễm khuẩn phụ khoa và tiết niệu.',
       'Cefdinir 300mg (Cefnirvid)', false,
       ARRAY['cefdinir', 'cefnirvid300(cefdinir)']::text[]),
      ('Cetrotide', 'SP000061', 1000000, NULL,
       'Tiêm dưới da',
       'Tiêm dưới da bụng 1 lọ mỗi ngày theo lịch hẹn chính xác của bác sĩ hỗ trợ sinh sản.',
       'Kháng GnRH ngăn ngừa phóng noãn sớm trong chu kỳ kích thích buồng trứng thụ tinh ống nghiệm.',
       'Cetrotide 0.25mg (Cetrorelix)', false,
       ARRAY['cetrotide']::text[]),
      ('Coq10 blackmores', 'SP000114', 520000, 'lọ',
       'Uống',
       'Ngày uống 1 - 2 lần, mỗi lần 1 viên sau bữa ăn có chất béo.',
       'Chất chống oxy hóa tế bào, cải thiện năng lượng ty thể của nang noãn và tinh trùng.',
       'CoQ10 Blackmores / Puritan (100mg - 200mg)', false,
       ARRAY['coq10(1/2)', 'coq10blackmores']::text[]),
      ('Cumlaude lab lubripiu viên đặt', 'SP000128', 500000, 'hộp',
       'Đặt âm đạo',
       'Tuần đặt 2 - 3 lần, mỗi lần 1 viên vào buổi tối.',
       'Cấp ẩm sâu kéo dài với phức hợp Hyaluronic acid cho phụ nữ bị khô rát âm đạo.',
       'Cumlaude Lab Lubripiu viên đặt', false,
       ARRAY['cumlaudelablubripiuviênđặt', 'cumlaudelubripiu(d)']::text[]),
      ('Cumlaude lubripiu (B)', NULL, 500000, 'hộp',
       'Bôi tại chỗ',
       'Thoa một lượng kem vừa đủ vào vùng âm hộ bên ngoài ngày 1 - 2 lần hoặc trước khi quan hệ.',
       'Chống đau rát khi sinh hoạt vợ chồng, làm mềm mại niêm mạc vùng kín.',
       'Cumlaude Lab Lubripiu kem bôi', true,
       ARRAY['cumlaudelubripiu(b)']::text[]),
      ('Cumlaude prebiotic', 'SP000100', 600000, 'hộp',
       'Đặt âm đạo',
       'Đặt 1 viên/ngày vào buổi tối trước khi đi ngủ trong 10 ngày liên tiếp, sau đó duy trì 1-2 viên/tuần.',
       'Cân bằng hệ vi sinh âm đạo, bổ sung prebiotic nuôi dưỡng khuẩn có lợi Lactobacillus.',
       'Cumlaude Lab Prebiotic viên đặt', false,
       ARRAY['cumlaudeprebiotic']::text[]),
      ('Daikyn 0.5mg (estriol)', '4840456000324', 270000, 'hộp',
       'Đặt âm đạo / Bôi',
       'Mỗi lần đặt 1 viên (hoặc bôi 1 lượng nhỏ), tuần 2 lần vào buổi tối trước khi đi ngủ.',
       'Điều trị teo khô niêm mạc âm đạo - âm hộ tiền mãn kinh, chống đau rát khi quan hệ.',
       'Daikyn 0.5mg (Estriol)', false,
       ARRAY['daikyn', 'daikyn0.5mg(estriol)']::text[]),
      ('Dalacin C', 'SP000017', 190000, 'hộp',
       'Uống',
       'Ngày uống 2 lần, mỗi lần 1 viên sau ăn sáng và tối. Đợt dùng 7 ngày.',
       'Đặc trị viêm âm đạo do vi khuẩn kỵ khí (Bacterial Vaginosis / Gardnerella vaginalis).',
       'Dalacin C 300mg (Clindamycin)', false,
       ARRAY['dalacinc']::text[]),
      ('Dermolivo gel', 'SP000129', 550000, 'hộp',
       'Bôi ngoài da',
       'Ngày bôi 1 - 2 lần vào vùng âm hộ, tiền đình hoặc vết nứt kẽ sau vệ sinh.',
       'Làm dịu ngứa rát, chống kích ứng, phục hồi vết thương vi mô.',
       'Dermolivo Gel bôi', false,
       ARRAY['dermolivogel']::text[]),
      ('Dermolivo viên đặt', 'SP000086', 550000, 'hộp',
       'Đặt âm đạo',
       'Tuần đặt 2 - 3 lần, mỗi lần 1 viên vào buổi tối sau khi vệ sinh sạch sẽ.',
       'Dưỡng ẩm tự nhiên từ dầu olive ozone hóa, tái tạo biểu mô âm đạo bị teo khô, trợt loét.',
       'Dermolivo viên đặt âm đạo', false,
       ARRAY['dermolivo(d)', 'dermolivoviênđặt']::text[]),
      ('DHA NataPure', 'SP000006', 360000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên sau bữa ăn tối hoặc trước khi đi ngủ.',
       'Phát triển não bộ, thị giác của thai nhi và hỗ trợ giấc ngủ cho mẹ bầu.',
       'DHA NataPure / BioIsland DHA', false,
       ARRAY['dha', 'dhanatapure']::text[]),
      ('DHEA Avemos', 'SP000005', 390000, 'hộp',
       'Uống / Đặt',
       'Ngày uống 1 lần, mỗi lần 1 viên. Sáng 1 viên sau ăn 30 phút. Hoặc đặt âm đạo theo chỉ định chuyên sâu.',
       'Hỗ trợ cải thiện chất lượng nang noãn, dự trữ buồng trứng AMH và nội tiết sinh sản.',
       'DHEA Avemos / Puritan', false,
       ARRAY['dhea(d/u)', 'dheaavemos']::text[]),
      ('Diane', 'SP000055', 160000, 'hộp',
       'Uống',
       'Uống 1 viên/ngày bắt đầu từ ngày 1 chu kỳ kinh trong 21 ngày liên tiếp, nghỉ 7 ngày rồi sang vỉ mới.',
       'Trị mụn trứng cá, rậm lông do buồng trứng đa nang (PCOS) và tránh thai.',
       'Diane-35 (Cyproterone + Ethinylestradiol)', false,
       ARRAY['diane', 'dianne']::text[]),
      ('Dienosis 2mg hộp 28 viên', 'SP000070', 850000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên, liên tục hằng ngày không ngắt quãng, uống cố định vào 1 giờ nhất định.',
       'Đặc trị lạc nội mạc tử cung, đau bụng kinh mạn tính. Uống liên tục cả trong chu kỳ hành kinh.',
       'Dienosis 2mg (Dienogest)', false,
       ARRAY['dienosis', 'dienosis2mghộp28viên']::text[]),
      ('Difavon', NULL, 280000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên sau ăn sáng.',
       'Giảm kích thích bàng quang, giảm đau rát vùng chậu.',
       'Diflavon (Flavoxate)', true,
       ARRAY['difavon']::text[]),
      ('Diflucan', NULL, 150000, 'hộp',
       'Uống',
       'Uống 1 viên duy nhất với 1 cốc nước lọc lớn sau ăn. Trường hợp nấm tái phát: uống viên thứ 2 sau 72 giờ.',
       'Thuốc đầu tay điều trị nấm âm đạo Candida cấp tính.',
       'Diflucan 150mg (Fluconazole chính hãng Pfizer)', true,
       ARRAY['diflucan']::text[]),
      ('Dipherelin 0.1', 'SP000056', 220000, NULL,
       'Tiêm',
       'Loại 0.1mg: Tiêm dưới da hằng ngày. Loại 3.75mg: Tiêm bắp 1 mũi duy nhất mỗi 28 ngày.',
       'Đồng vận GnRH hạ điều hòa tuyến yên trong IVF hoặc điều trị lạc nội mạc tử cung, u xơ.',
       'Diphereline (Triptorelin)', false,
       ARRAY['dipherelin0.1']::text[]),
      ('Dipherelin 3.75', 'Dipherelin 3.75', 3400000, 'hộp',
       'Tiêm',
       'Loại 0.1mg: Tiêm dưới da hằng ngày. Loại 3.75mg: Tiêm bắp 1 mũi duy nhất mỗi 28 ngày.',
       'Đồng vận GnRH hạ điều hòa tuyến yên trong IVF hoặc điều trị lạc nội mạc tử cung, u xơ.',
       'Diphereline (Triptorelin)', false,
       ARRAY['dipherelin3.75', 'diphereline(3.75/0.1)']::text[]),
      ('Docyxycline', 'SP000057', 1500, 'viên',
       'Uống',
       'Ngày uống 2 lần, mỗi lần 1 viên sau ăn sáng và tối. Uống cùng nhiều nước và ngồi thẳng 30 phút.',
       'Kháng sinh diệt Ureaplasma parvum, Chlamydia. Tuyệt đối không nằm ngay sau uống để tránh loét thực quản.',
       'Doxycycline 100mg', false,
       ARRAY['docy(15v/30v)', 'docyxycline']::text[]),
      ('Dunium (clomiphen citrat)', 'SP000121', 10000, 'viên',
       'Uống',
       'Uống 1 - 2 viên/ngày x 5 ngày liên tục theo lịch hẹn của bác sĩ.',
       'Kích thích nang trứng phát triển.',
       'Fetogard (Clomiphene 50mg)', false,
       ARRAY['dunium(clomiphencitrat)', 'dunium/fetogard(10v/15v)']::text[]),
      ('Duphaston', 'SP000009', 240000, 'hộp',
       'Uống',
       'Ngày uống 2 - 4 viên chia 2 lần (sáng - tối) sau ăn. Uống từ ngày thứ 14 đến ngày 25 của chu kỳ kinh, hoặc dùng liên tục trong dọa sảy thai.',
       'Điều hòa kinh nguyệt, hỗ trợ hoàng thể, an thai an toàn không gây ức chế rụng trứng.',
       'Duphaston 10mg (Dydrogesterone)', false,
       ARRAY['duphaston', 'duphaston(4v/2v)']::text[]),
      ('durapil', 'SP000041', 1200000, 'hộp',
       'Uống',
       'Uống 1 viên với 1 cốc nước đầy trước khi quan hệ 1 - 2 giờ.',
       'Đặc trị xuất tinh sớm cho nam giới. Không dùng chung với rượu bia.',
       'Durapil 30mg (Dapoxetine)', false,
       ARRAY['durapil']::text[]),
      ('Ecanix D3', 'SP000108', 550000, 'hộp 60 viên',
       'Uống',
       'Ngày uống 1 - 2 lần, mỗi lần 1 viên. Uống sau ăn sáng hoặc sau ăn trưa trước 15h.',
       'Không uống canxi vào buổi tối. Uống cách xa viên Sắt tối thiểu 2 tiếng.',
       'Procalcium / Green Calcium / Calci Citrate', false,
       ARRAY['canxi', 'ecanixd3']::text[]),
      ('Eluna', 'SP000032', 500000, NULL,
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['eluna']::text[]),
      ('Endokirogen', 'SP000023', 950000, 'hộp',
       NULL,
       'Ngày uống 1 lần, mỗi lần uống 1 gói sau ăn',
       NULL,
       NULL, false,
       ARRAY['endokirogen']::text[]),
      ('Espana mama', 'SP000112', NULL, 'hộp',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['espanamama']::text[]),
      ('Estrogel', NULL, 550000, 'hộp',
       'Bôi ngoài da',
       'Sáng thức dậy bôi 1 lần, mỗi lần 1 thước đo (hoặc 1 pump). Thoa đều lên diện tích rộng vùng cánh tay, vai hoặc đùi.',
       'Không thoa lên ngực hoặc niêm mạc âm đạo. Rửa sạch tay sau khi bôi.',
       'Estrogel (Estradiol gel)', true,
       ARRAY['estrogel']::text[]),
      ('Estrogel pump', 'SP000031', 550000, 'hộp',
       'Bôi ngoài da',
       'Mỗi ngày 1 - 2 nhát xịt (pump) vào buổi sáng. Thoa mỏng lên vùng da sạch, khô ở cánh tay, đùi hoặc bả vai.',
       'Hỗ trợ nội tiết estrogen tự nhiên, cải thiện bốc hỏa, mất ngủ, teo niêm mạc.',
       'Estrogel pump (Estradiol 0.06%)', false,
       ARRAY['estrogelpump']::text[]),
      ('Eulac', 'SP000097', 280000, 'hộp',
       'Đặt âm đạo',
       'Tuần đặt 2 lần (hoặc 1 viên/ngày x 6 ngày), tối sau khi vệ sinh vùng kín.',
       'Phục hồi hệ khuẩn chí âm đạo và tái tạo niêm mạc sau điều trị kháng sinh/kháng nấm.',
       'Eulac / Gynoflor (Lactobacillus + Estriol)', false,
       ARRAY['eulac']::text[]),
      ('Femoston 1/10', 'SP000007', 740000, NULL,
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên cố định giờ. Uống liên tục 14 viên trắng đầu, sau đó chuyển sang 14 viên xám.',
       'Liệu pháp hormone thay thế HRT theo chu kỳ cho phụ nữ quanh mãn kinh còn tử cung.',
       'Femoston 1/10 (Estradiol + Dydrogesterone)', false,
       ARRAY['femoston1/10', 'fes1/10']::text[]),
      ('Femoston 1/5', 'SP000063', 1100000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên, uống liên tục hằng ngày không nghỉ, uống cố định vào 1 khung giờ.',
       'Liệu pháp hormone phối hợp liên tục cho phụ nữ đã mãn kinh hoàn toàn (> 12 tháng).',
       'Femoston 1/5 (Estradiol + Dydrogesterone liên tục)', false,
       ARRAY['femoston1/5', 'fes1/5']::text[]),
      ('Fersen', 'SP000122', 950000, 'hộp',
       'Uống',
       'Ngày uống 1 - 2 gói, pha với 100-150ml nước lọc uống sau bữa ăn sáng và tối.',
       'Bổ sung L-Carnitine, Arginine, Kẽm cải thiện mật độ và tốc độ bơi của tinh trùng.',
       'Fersen (Hộp 30 gói)', false,
       ARRAY['fersen']::text[]),
      ('Filrosy (progesteron 200mg)', 'SP000127', 25000, 'viên',
       'Đặt âm đạo',
       'Ngày đặt âm đạo 1 lần, mỗi lần 1 viên. Đặt sâu vào âm đạo vào buổi tối trước khi đi ngủ sau khi vệ sinh vùng kín.',
       'Nằm nghỉ ngơi tại chỗ tối thiểu 30 phút sau khi đặt. Giữ thuốc nơi thoáng mát hoặc ngăn mát tủ lạnh.',
       'Filrosy (Progesterone 200mg)', false,
       ARRAY['filrosy(progesteron200mg)', 'filrosyprogesteron200(d)']::text[]),
      ('Flepgo 100mg', 'SP000090', 420000, 'hộp',
       'Uống',
       'Uống 1 viên trước khi quan hệ tình dục 15 - 30 phút.',
       'Thuốc giãn mạch thế hệ mới tác dụng nhanh, hỗ trợ cương dương cho nam giới.',
       'Flepgo 100mg (Avanafil)', false,
       ARRAY['avanafil(flepgo100)', 'flepgo100mg']::text[]),
      ('Fluconazole', 'SP000043', 5000, 'hộp 1 viên',
       'Uống',
       'Uống 1 viên duy nhất sau ăn no.',
       'Thuốc kháng nấm toàn thân.',
       'Fluconazole 150mg', false,
       ARRAY['fluconazole']::text[]),
      ('Fluomizin ( 6 viên đặt )', 'SP000034', 280000, NULL,
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['fluomizin(6viênđặt)']::text[]),
      ('Folic mum', 'SP000103', 260000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên sau ăn sáng.',
       'Phòng ngừa dị tật ống thần kinh thai nhi, uống trước thụ thai tối thiểu 1-3 tháng.',
       'Folic Mum / Acid Folic 400mcg', false,
       ARRAY['folicmum']::text[]),
      ('Follitrope', NULL, 850000, 'ống',
       'Tiêm dưới da',
       'Tiêm dưới da bụng theo liều lượng chỉ định riêng và đúng khung giờ mỗi ngày.',
       'Hormone kích thích nang noãn phát triển trong chu kỳ IVF / IUI.',
       'Follitrope 300IU / 150IU (r-FSH)', true,
       ARRAY['follintrope', 'follitrope']::text[]),
      ('Fosamax plus 70/5600', 'SP000033', 500000, 'hộp',
       NULL,
       'Tuần uống 1 lần, mỗi lần uống 1 viên. Uống trước bữa ăn và uống cùng nhiều nước lọc. Sau uống ngồi thẳng yên 30 phút',
       NULL,
       NULL, false,
       ARRAY['fosamaxplus70/5600']::text[]),
      ('Fosamax plus 70mg/2800iu', 'SP000091', 450000, 'Hộp',
       'Uống',
       'Mỗi tuần uống duy nhất 1 viên vào 1 ngày cố định. Uống ngay khi thức dậy với 1 cốc nước lọc đầy (200ml).',
       'QUAN TRỌNG: Không được nằm trong vòng 30 phút sau uống, không nhai viên thuốc, không ăn sáng hoặc uống thuốc khác trong 30 phút đầu.',
       'Fosamax Plus (Alendronate + Vitamin D3)', false,
       ARRAY['fosamax2800/5600', 'fosamaxplus70mg/2800iu']::text[]),
      ('Gemapaxane', 'SP000054', 85000, 'bơm',
       'Tiêm dưới da',
       'Tiêm dưới da thành bụng 1 bơm (0.4ml) mỗi ngày vào 1 giờ cố định.',
       'Kháng đông trọng lượng phân tử thấp dự phòng huyết khối và sẩy thai liên tiếp.',
       'Gemapaxane 4000IU / Lovenox (Enoxaparin)', false,
       ARRAY['gemapaxan', 'gemapaxane']::text[]),
      ('Glucophage XR 750mg', 'SP000025', 140000, 'hộp',
       'Uống',
       'Ngày uống 1 - 2 viên vào buổi tối sau bữa ăn no để giảm tác dụng phụ trên đường tiêu hóa.',
       'Cải thiện đề kháng insulin ở bệnh nhân buồng trứng đa nang (PCOS), hỗ trợ phóng noãn.',
       'Glucophage XR 750mg / 500mg (Metformin)', false,
       ARRAY['glucophage', 'glucophagexr750mg']::text[]),
      ('GonalF', NULL, 1200000, 'bút',
       'Tiêm dưới da',
       'Tiêm dưới da bằng bút tiêm chuyên dụng, xoay đúng nấc liều bác sĩ chỉ định.',
       'Bảo quản bút tiêm trong ngăn mát tủ lạnh (2 - 8 độ C).',
       'Gonal-F 300 / 450 / 900 (Follitropin alfa)', true,
       ARRAY['gonalf']::text[]),
      ('Indole', 'SP000120', 600000, 'hộp',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['indole']::text[]),
      ('Indurat 20mg', 'SP000119', 50000, 'viên',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['indurat20mg']::text[]),
      ('Indurat 5mg', 'SP000118', 33000, 'viên',
       'Uống / Đặt',
       'Ngày uống 1 lần, mỗi lần 1 viên sau ăn. Hoặc đặt âm đạo làm tăng tuần hoàn tưới máu tử cung buồng trứng.',
       'Tăng tưới máu niêm mạc tử cung cho phụ nữ niêm mạc mỏng, chuẩn bị chuyển phôi.',
       'Indurat 5mg / Tadalafil', false,
       ARRAY['indurat5mg', 'indurate5(d/u)']::text[]),
      ('Intimate', 'SP000037', 200000, 'hộp',
       'Rửa ngoài',
       'Dùng vệ sinh bên ngoài vùng kín ngày 1 - 2 lần khi tắm.',
       'Độ pH sinh lý, không thụt rửa sâu vào trong âm đạo.',
       'Dung dịch vệ sinh Ziaja Intimate', false,
       ARRAY['intimate']::text[]),
      ('Ivf C 5000', 'SP000065', 300000, NULL,
       'Tiêm bắp / Tiêm dưới da',
       'Tiêm 1 liều duy nhất chính xác vào giờ bác sĩ hẹn (mũi tiêm rụng trứng).',
       'Kích hoạt trưởng thành noãn cuối cùng trước khi chọc hút trứng 36 giờ hoặc trước IUI 36-40 giờ.',
       'IVF-C 5000 IU (hCG)', false,
       ARRAY['ivf-c', 'ivfc5000']::text[]),
      ('IVF M 150', 'SP000047', 750000, NULL,
       'Tiêm bắp / Tiêm dưới da',
       'Tiêm hàng ngày theo liều lượng chỉ định của bác sĩ chuyên khoa.',
       'Chứa cả FSH và LH giúp nang noãn phát triển đồng đều.',
       'IVF-M 75 / 150 IU (hMG - Menotropin)', false,
       ARRAY['ivf-m', 'ivfm150']::text[]),
      ('Kim thử đường máu Accuchek instant', 'SP000110', 2000, 'cái',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['kimthửđườngmáuaccuchekinstant']::text[]),
      ('King Seal', 'SP000048', 930000, 'hộp',
       NULL,
       'Ngày uống 3 lần, mỗi lần 1 viên. Sáng 1 viên, trưa 1 viên, tối 1 viên sau ăn.',
       NULL,
       NULL, false,
       ARRAY['kingseal']::text[]),
      ('Kofio (estriol)', 'SP000101', 225000, 'hộp 15 viên',
       'Đặt âm đạo',
       'Tuần đặt âm đạo 2 viên vào buổi tối trước khi đi ngủ. Đặt cách ngày hoặc theo chỉ dẫn.',
       'Bảo quản trong ngăn mát tủ lạnh để viên thuốc giữ độ cứng dễ đặt.',
       'Kofio (Estriol viên đặt)', false,
       ARRAY['kofio', 'kofio(estriol)']::text[]),
      ('Letrozole (Femara) (10v/15v)', NULL, 50000, 'viên',
       'Uống',
       'Ngày uống 1 - 2 viên (sáng 1 viên, chiều 1 viên) từ ngày 2 hoặc 3 chu kỳ kinh, liên tục 5 ngày.',
       'Kích trứng thế hệ mới hiệu quả vượt trội cho phụ nữ buồng trứng đa nang PCOS.',
       'Femara 2.5mg (Letrozole)', true,
       ARRAY['letrozole(femara)(10v/15v)']::text[]),
      ('Levina 5', 'SP000106', 300000, 'hộp',
       'Uống',
       'Ngày uống 1 viên sau ăn.',
       'Cải thiện vi tuần hoàn hoặc giảm phản ứng dị ứng theo chỉ định lâm sàng.',
       'Levina 5mg (Levocetirizine / Vardenafil)', false,
       ARRAY['levina5']::text[]),
      ('Lomexin 200mg', 'SP000066', 150000, 'hộp',
       'Đặt âm đạo',
       'Loại 600mg: Đặt 1 viên duy nhất vào buổi tối. Loại 200mg: Đặt 1 viên/ngày trong 3 ngày.',
       'Kháng nấm phổ rộng tại chỗ.',
       'Lomexin 200mg / 600mg (Fenticonazole)', false,
       ARRAY['lomexin', 'lomexin200mg']::text[]),
      ('Magnella', 'SP000084', 285000, 'hộp',
       'Uống',
       'Ngày uống 1 - 2 lần, mỗi lần 1 viên. Uống buổi tối sau ăn để cải thiện chất lượng giấc ngủ.',
       'Giảm chuột rút, giảm co thắt tử cung, thư giãn thần kinh, chống đau đầu chóng mặt.',
       'Magie Max / Magne B6', false,
       ARRAY['magie', 'magnella']::text[]),
      ('Meclon', 'SP000020', 250000, NULL,
       'Đặt âm đạo',
       'Ngày đặt 1 viên vào buổi tối trước khi đi ngủ, liên tục trong 6 - 10 ngày.',
       'Phối hợp trị viêm âm đạo hỗn hợp do Trichomonas và Candida.',
       'Meclon viên đặt (Metronidazole + Clotrimazole)', false,
       ARRAY['meclon']::text[]),
      ('Mensterona', NULL, 950000, 'hộp',
       'Uống',
       'Ngày uống 1 - 2 gói (hoặc 2 viên), chia sáng và tối sau ăn.',
       'Tăng số lượng, độ di động tiến tới và hình thái tinh trùng cho nam giới.',
       'Mensterona / King Seal', true,
       ARRAY['mensterona']::text[]),
      ('Metronidazol', 'SP000050', 1000, 'viên',
       'Uống',
       'Ngày uống 2 lần, mỗi lần 2 viên (500mg) sau ăn sáng và tối trong 7 ngày.',
       'QUAN TRỌNG: Tuyệt đối kiêng rượu bia, đồ uống có cồn trong suốt thời gian uống và 48h sau đó.',
       'Metronidazole 250mg / 500mg', false,
       ARRAY['metronidazol', 'metronidazole']::text[]),
      ('Máy đo đường huyết ACCU-CHEK Instant', 'SP000039', 1050000, 'cái',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['máyđođườnghuyếtaccu-chekinstant']::text[]),
      ('Ovagrow', 'SP000011', 550000, 'hộp',
       'Uống',
       'Ngày uống 1 - 2 gói (hoặc viên) sau bữa ăn sáng và tối.',
       'Cân bằng nội tiết, phục hồi chu kỳ rụng trứng tự nhiên cho phụ nữ PCOS.',
       'Ovagrow (Myo-inositol + D-chiro-inositol)', false,
       ARRAY['ovagrow']::text[]),
      ('Ovitrelle', 'SP000067', 1300000, 'hộp',
       'Tiêm dưới da',
       'Tiêm dưới da 1 bút tiêm duy nhất chính xác đến từng phút theo chỉ định của bác sĩ.',
       'Mũi tiêm rụng trứng kích hoạt noãn trưởng thành trước chọc hút trứng hoặc IUI.',
       'Ovitrelle 250mcg (Choriogonadotropin alfa)', false,
       ARRAY['ovitrelle']::text[]),
      ('Ozempic 0.25/0.5', 'SP000123', 5000000, 'bút',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['ozempic0.25/0.5']::text[]),
      ('Ozempic 1mg', 'SP000124', 5000000, 'bút',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['ozempic1mg']::text[]),
      ('Probiotics plus for men', 'SP000107', 1000000, 'hộp',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['probioticsplusformen']::text[]),
      ('Pruzena', 'SP000021', 120000, 'hộp',
       'Uống',
       'Uống 1 - 2 viên vào buổi tối trước khi đi ngủ. Trường hợp nghén nặng: thêm 1 viên buổi sáng.',
       'Đặc trị nghén, buồn nôn, nôn mửa trong thai kỳ quý I an toàn tuyệt đối.',
       'Pruzena (Doxylamine + Pyridoxine B6)', false,
       ARRAY['pruzena']::text[]),
      ('Que thử tiểu đường Accu-check Instant (hộp 25 que)', 'SP000038', 250000, 'hộp 25 que',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['quethửtiểuđườngaccu-checkinstant(hộp25que)']::text[]),
      ('Tadal extra 20mg', 'SP000092', 100000, 'hộp 2 viên',
       'Uống',
       'Loại 5mg: Uống 1 viên/ngày sau ăn. Loại 20mg: Uống 1 viên trước khi quan hệ 30 - 60 phút.',
       'Tăng tưới máu cơ quan sinh dục, hỗ trợ niêm mạc tử cung ở nữ và cương dương ở nam.',
       'Tadalafil 5mg / 20mg', false,
       ARRAY['tadalextra20mg']::text[]),
      ('Tadalafin 5mg', 'SP000035', 380000, 'hộp',
       'Uống',
       'Loại 5mg: Uống 1 viên/ngày sau ăn. Loại 20mg: Uống 1 viên trước khi quan hệ 30 - 60 phút.',
       'Tăng tưới máu cơ quan sinh dục, hỗ trợ niêm mạc tử cung ở nữ và cương dương ở nam.',
       'Tadalafil 5mg / 20mg', false,
       ARRAY['tadalafil5/20', 'tadalafin5mg']::text[]),
      ('Triclofem', 'SP000093', 180000, 'lọ',
       NULL,
       NULL,
       NULL,
       NULL, false,
       ARRAY['triclofem']::text[]),
      ('Usartestos', 'SP000126', 20000, 'viên',
       'Đặt âm đạo',
       'Tuần đặt 2 lần, mỗi lần 1 viên vào buổi tối theo chỉ định nghiêm ngặt của bác sĩ.',
       'Điều trị rối loạn chức năng tình dục nữ, cải thiện ham muốn và bôi trơn âm đạo.',
       'Usartestos (Testosterone viên đặt)', false,
       ARRAY['usartestos', 'usatestos(d)']::text[]),
      ('Utrogestan 100mg', 'SP000117', 255000, 'hộp',
       'Đặt âm đạo / Uống',
       'Ngày 1 - 2 lần, mỗi lần 1 viên. Ưu tiên đặt âm đạo buổi tối để tránh cảm giác chóng mặt, buồn ngủ khi uống.',
       'Dưỡng thai, hỗ trợ hoàng thể pha 2 chu kỳ kinh.',
       'Utrogestan 100mg', false,
       ARRAY['utrogestan100mg', 'utrogestran100(d/u)(1v/2v)']::text[]),
      ('Utrogestan 200', 'SP000022', 255000, 'hộp',
       'Đặt âm đạo / Uống',
       'Ngày đặt âm đạo 1 - 2 lần, mỗi lần 1 viên. Sáng 1 viên, tối 1 viên sau khi vệ sinh sạch sẽ.',
       'Dọa sẩy thai, dọa sinh non hoặc hỗ trợ sau chuyển phôi IVF.',
       'Utrogestan 200mg', false,
       ARRAY['utrogestan200', 'utrogestran200(d/u)(1v/2v)']::text[]),
      ('Valiera', 'SP000058', 120000, 'hộp',
       'Đặt âm đạo / Uống',
       'Tuần đặt 2 - 3 lần, mỗi lần đặt 1 viên vào buổi tối trước khi đi ngủ. Hoặc uống ngày 1 - 3 viên theo phác đồ làm dày niêm mạc.',
       'Bổ sung estrogen làm dày niêm mạc tử cung và cải thiện teo khô âm đạo.',
       'Valiera (Estradiol 2mg)', false,
       ARRAY['valiera', 'valiera(d/u)(1v/2v/3v)']::text[]),
      ('Venice 5MTHF', 'SP000052', 360000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên sau bữa ăn sáng.',
       'Dạng folate hoạt tính sinh học trực tiếp, tối ưu cho người có đột biến gen MTHFR, chuẩn bị mang thai.',
       'Venice 5-MTHF / Quatrefolic', false,
       ARRAY['5-mthf', 'venice5mthf']::text[]),
      ('Vitcofol', 'SP000014', 220000, 'hộp',
       'Uống',
       'Ngày uống 1 lần, mỗi lần 1 viên. Uống trước bữa ăn 30 phút hoặc sau ăn 1 tiếng.',
       'Uống với nước cam hoặc nước lọc giàu Vitamin C. Uống cách xa Canxi tối thiểu 2 tiếng.',
       'Vitcofol (Sắt hữu cơ + Vitamin nhóm B)', false,
       ARRAY['vitcofol']::text[]),
      ('Viên đặt nystatin 100.000ui', 'SP000105', 20000, 'hộp',
       'Đặt âm đạo',
       'Ngày đặt 1 - 2 lần, mỗi lần 1 viên, liên tục trong 14 ngày.',
       'Làm ẩm viên thuốc với nước 1-2 giây trước khi đặt sâu vào âm đạo.',
       'Nystatin 100.000 UI viên đặt', false,
       ARRAY['nystatin', 'viênđặtnystatin100.000ui']::text[]),
      ('Voltaren', 'SP000051', NULL, NULL,
       NULL,
       'Đặt 1 viên đường hậu môn trước thủ thuật',
       NULL,
       NULL, false,
       ARRAY['voltaren']::text[]),
      ('Yspuripax', 'SP000002', 7000, 'viên',
       'Uống',
       'Ngày uống 2 - 3 lần, mỗi lần 1 - 2 viên sau ăn.',
       'Chống co thắt cơ trơn đường tiết niệu, giảm tiểu buốt, tiểu rắt, đau bàng quang.',
       'Yspuripax 200mg (Flavoxate HCl)', false,
       ARRAY['yspuripax', 'yspuripax(2v/4v)']::text[]),
      ('Zincodin', 'SP000113', 275000, 'hộp',
       'Uống',
       'Ngày uống 1 viên sau ăn trưa hoặc sáng.',
       'Tăng cường miễn dịch, làm dày niêm mạc, hỗ trợ chức năng buồng trứng và tinh hoàn.',
       'Zincodin / Zinc Puritan', false,
       ARRAY['zinc', 'zincodin']::text[]),
      ('Zolmed', NULL, 180000, 'hộp',
       'Uống',
       'Uống 1 liều duy nhất 2g (2 viên) vào đầu bữa ăn.',
       'Điều trị viêm âm đạo do Gardnerella, Trichomonas liều duy nhất.',
       'Zolmed (Secnidazole 1g / 2g)', true,
       ARRAY['zolmed']::text[])
      ) AS v(ten, ma_hang, gia, don_vi, duong_dung, cach_dung, luu_y, biet_duoc,
             can_soat, khoa)
    LOOP
      SELECT d.id INTO id_co
        FROM public.drug_catalog d
       WHERE d.clinic_id = c.id
         AND regexp_replace(lower(d.name_raw), '\s', '', 'g') = ANY (r.khoa)
         AND NOT (d.id = ANY (chon))
       ORDER BY (d.name_raw = r.ten) DESC,
                (regexp_replace(lower(d.name_raw), '\s', '', 'g')
                   = regexp_replace(lower(r.ten), '\s', '', 'g')) DESC,
                d.is_active DESC, d.created_at, d.id
       LIMIT 1;
      IF id_co IS NULL THEN
        INSERT INTO
            public.drug_catalog
            (clinic_id, name_raw, name_base, unit_price, needs_review, is_active,
             ma_hang, don_vi_ban, duong_dung, cach_dung, luu_y, biet_duoc)
        VALUES (c.id, r.ten, r.ten, r.gia, r.can_soat, true,
                r.ma_hang, r.don_vi, r.duong_dung, r.cach_dung, r.luu_y, r.biet_duoc)
        RETURNING id INTO id_co;
      ELSE
        UPDATE public.drug_catalog
           SET name_raw = r.ten, name_base = r.ten, unit_price = r.gia,
               needs_review = r.can_soat, is_active = true,
               ma_hang = r.ma_hang, don_vi_ban = r.don_vi,
               duong_dung = r.duong_dung, cach_dung = r.cach_dung,
               luu_y = r.luu_y, biet_duoc = r.biet_duoc
         WHERE id = id_co;
      END IF;
      chon := chon || id_co;
    END LOOP;

    UPDATE public.drug_catalog
       SET is_active = false
     WHERE clinic_id = c.id AND is_active AND NOT (id = ANY (chon));

    UPDATE public.service_price
       SET active = false
     WHERE clinic_id = c.id AND "group" = 'thuoc' AND active;
  END LOOP;
END;
$$;

-- CHỈ trên DB ĐANG CHẠY (đã có nhân sự — prod). DB dựng mới chạy migration
-- TRƯỚC seed: chuẩn hoá lúc ấy sẽ thêm "Vitcofol"… rồi seed chèn lại đúng tên
-- ấy → trùng khoá. Ở đó seed.sql tự gọi hàm sau khi nạp dữ liệu.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.staff) THEN
    PERFORM public.chuan_hoa_danh_muc_thuoc_kiotviet();
  END IF;
END;
$$;
